name: site
description: Felipe Sales | Social Links.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  # dart_code_metrics: ^5.7.6
  firebase_analytics: ^10.4.4
  firebase_core: ^2.15.0
  firebase_core_platform_interface: ^4.8.0
  firebase_core_web: ^2.6.0
  firebase_remote_config: ^4.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  http: ^1.1.0
  intl: ^0.18.0
  lottie: ^2.6.0
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.1.12
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/components/
    - assets/components/contact/
    - assets/components/experience/
    - assets/components/presentation/
    - assets/components/projects/
    - assets/components/social/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
  generate: true
