name: site
description: Felipe Sales | Social Links.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  firebase_analytics: ^9.1.7
  firebase_core: ^1.16.0
  flutter:
    sdk: flutter
  google_fonts: ^2.3.2
  url_launcher: ^6.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
